//
//  Untitled.swift
//  teslaDashcamViewer
//
//  Created by Connor Lin on 8/15/25.
//

import SwiftData
import Foundation

@Model
final class Event {
    // All fields have defaults so the type is CloudKit-syncable.
    var source: String = "Unknown"
    var camera: String = ""
    var city: String = ""
    var estLatitude: String = ""
    var estLongitude: String = ""
    var reason: String = ""
    var timestamp: Date = Date.distantPast

    /// Composite interestingness score (0..1+). Higher = more notable.
    var interestingnessScore: Double = 0

    /// One of: "touched", "lingered", "approached", "passing", "vehicle", "noise", "unknown".
    var tag: String = "unknown"

    /// Natural-language summary generated by the on-device foundation model.
    var summary: String = ""

    /// Reverse-geocoded street address (cached after the first lookup).
    var address: String = ""

    /// Name of the matching Geofence (e.g. "Home"), empty if none.
    var zone: String = ""

    /// User-marked favorite for quick filtering.
    var isFavorite: Bool = false

    /// Free-form user notes.
    var notes: String = ""

    /// Archived events are hidden from the default list view.
    var isArchived: Bool = false

    init(source: String, camera: String, city: String, estLatitude: String, estLongitude: String, reason: String, timestamp: Date, interestingnessScore: Double = 0, tag: String = "unknown", summary: String = "") {
        self.source = source
        self.camera = camera
        self.city = city
        self.estLatitude = estLatitude
        self.estLongitude = estLongitude
        self.reason = reason
        self.timestamp = timestamp
        self.interestingnessScore = interestingnessScore
        self.tag = tag
        self.summary = summary
    }
}
